import type {
  ClarifyingQuestion,
  PracticeSession,
  Question,
  TopicMastery,
  UserProfile,
} from "@/types"

// ---------------------------------------------------------------------------
// Realistic mock content for the CertForge prototype. In production these
// would be generated by the AI backend; here they power a fully interactive UI.
// ---------------------------------------------------------------------------

export const mockProfile: UserProfile = {
  name: "Jordan Avery",
  email: "jordan@certforge.app",
  plan: "free",
  dailyLimit: 20,
  questionsUsedToday: 8,
  streakDays: 12,
}

export const mockTopicMastery: TopicMastery[] = [
  { topic: "Networking", mastery: 48, questionsAnswered: 64 },
  { topic: "Security & Identity", mastery: 56, questionsAnswered: 72 },
  { topic: "Storage", mastery: 81, questionsAnswered: 90 },
  { topic: "Compute", mastery: 74, questionsAnswered: 58 },
  { topic: "Databases", mastery: 67, questionsAnswered: 41 },
  { topic: "Resilience", mastery: 62, questionsAnswered: 33 },
]

/** Mastery trend over the last 7 sessions, for the dashboard chart. */
export const mockMasteryTrend = [
  { label: "Mon", mastery: 52 },
  { label: "Tue", mastery: 55 },
  { label: "Wed", mastery: 54 },
  { label: "Thu", mastery: 61 },
  { label: "Fri", mastery: 63 },
  { label: "Sat", mastery: 66 },
  { label: "Sun", mastery: 68 },
]

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q1",
    topic: "Networking",
    difficulty: "medium",
    multiSelect: false,
    prompt:
      "A company runs a public-facing web application in a VPC. The security team requires that instances in the private subnet can download OS patches from the internet, but must not be reachable from the internet directly. Which solution meets these requirements?",
    options: [
      { id: "a", text: "Attach an internet gateway to the private subnet route table." },
      { id: "b", text: "Deploy a NAT gateway in a public subnet and route private subnet traffic through it." },
      { id: "c", text: "Assign Elastic IP addresses to each private instance." },
      { id: "d", text: "Create a VPC peering connection to a shared services VPC." },
    ],
    correctOptionIds: ["b"],
    explanation:
      "A NAT gateway lets instances in a private subnet initiate outbound connections to the internet (for patches, updates) while preventing the internet from initiating inbound connections. The NAT gateway lives in a public subnet, and the private subnet route table sends 0.0.0.0/0 to the NAT gateway. Attaching an internet gateway directly would make the subnet public, and Elastic IPs would expose the instances.",
    references: [
      { label: "AWS Docs — NAT gateways", url: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html" },
    ],
  },
  {
    id: "q2",
    topic: "Security & Identity",
    difficulty: "hard",
    multiSelect: true,
    prompt:
      "You need to grant an application running on an EC2 instance access to an S3 bucket following least-privilege best practices. Which TWO actions should you take?",
    options: [
      { id: "a", text: "Create an IAM role with a scoped S3 policy and attach it to the instance via an instance profile." },
      { id: "b", text: "Store long-lived IAM user access keys in the application's config file." },
      { id: "c", text: "Restrict the policy to the specific bucket and required actions only." },
      { id: "d", text: "Grant the role the AdministratorAccess managed policy for simplicity." },
    ],
    correctOptionIds: ["a", "c"],
    explanation:
      "Best practice is to use an IAM role attached through an instance profile so the application receives temporary, automatically-rotated credentials — never long-lived keys in config files. The attached policy should be scoped to only the specific bucket and the minimum actions required, which is the essence of least privilege. AdministratorAccess violates least privilege.",
    references: [
      { label: "AWS Docs — IAM roles for EC2", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html" },
    ],
  },
  {
    id: "q3",
    topic: "Storage",
    difficulty: "easy",
    multiSelect: false,
    prompt:
      "Which S3 storage class is most cost-effective for data that is accessed roughly once a quarter and must be retrieved within milliseconds when needed?",
    options: [
      { id: "a", text: "S3 Standard" },
      { id: "b", text: "S3 Standard-Infrequent Access (Standard-IA)" },
      { id: "c", text: "S3 Glacier Deep Archive" },
      { id: "d", text: "S3 One Zone-IA" },
    ],
    correctOptionIds: ["b"],
    explanation:
      "S3 Standard-IA is designed for data that is accessed less frequently but requires rapid (millisecond) access when needed. It has a lower storage cost than S3 Standard with a per-GB retrieval fee. Glacier Deep Archive has retrieval times of hours, and One Zone-IA sacrifices multi-AZ resilience.",
    references: [
      { label: "AWS Docs — S3 storage classes", url: "https://aws.amazon.com/s3/storage-classes/" },
    ],
  },
  {
    id: "q4",
    topic: "Resilience",
    difficulty: "medium",
    multiSelect: false,
    prompt:
      "An application must remain available even if an entire Availability Zone fails. Which architecture best achieves this for a stateless web tier behind a load balancer?",
    options: [
      { id: "a", text: "A single large EC2 instance with an Elastic IP." },
      { id: "b", text: "An Auto Scaling group spanning multiple AZs behind an Application Load Balancer." },
      { id: "c", text: "Two instances in the same AZ with a standby instance." },
      { id: "d", text: "A vertically scaled instance in one AZ with frequent snapshots." },
    ],
    correctOptionIds: ["b"],
    explanation:
      "Spreading an Auto Scaling group across multiple Availability Zones behind an Application Load Balancer ensures that if one AZ fails, the ALB routes traffic to healthy instances in the remaining AZs and Auto Scaling replaces unhealthy capacity. Single-AZ designs cannot survive an AZ failure.",
    references: [
      { label: "AWS Docs — Distributing instances across AZs", url: "https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html" },
    ],
  },
  {
    id: "q5",
    topic: "Databases",
    difficulty: "medium",
    multiSelect: false,
    prompt:
      "A read-heavy application using Amazon RDS for MySQL is experiencing high read latency during peak hours. Which change most directly improves read scalability without changing the application's write path?",
    options: [
      { id: "a", text: "Enable Multi-AZ deployment." },
      { id: "b", text: "Add RDS read replicas and direct read traffic to them." },
      { id: "c", text: "Increase the backup retention period." },
      { id: "d", text: "Switch the instance to a burstable instance class." },
    ],
    correctOptionIds: ["b"],
    explanation:
      "Read replicas offload read traffic from the primary, improving read scalability and lowering latency for read-heavy workloads. Multi-AZ is for high availability/failover (the standby does not serve reads), and increasing backup retention does not affect read performance.",
    references: [
      { label: "AWS Docs — RDS read replicas", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html" },
    ],
  },
]

export const mockClarifyingQuestions: ClarifyingQuestion[] = [
  {
    id: "c1",
    question: "Which exam attempt date are you targeting?",
    suggestions: ["Within 2 weeks", "1-2 months", "Just exploring"],
  },
  {
    id: "c2",
    question: "How would you rate your current networking knowledge?",
    suggestions: ["Beginner", "Intermediate", "Confident"],
  },
  {
    id: "c3",
    question: "Preferred question difficulty to start with?",
    suggestions: ["Mixed", "Mostly hard", "Ease me in"],
  },
]

const now = Date.now()
const day = 24 * 60 * 60 * 1000

function buildAnswers(
  questions: Question[],
  correctCount: number,
): PracticeSession["answers"] {
  const answers: PracticeSession["answers"] = {}
  questions.forEach((q, i) => {
    const isCorrect = i < correctCount
    answers[q.id] = {
      questionId: q.id,
      selectedOptionIds: isCorrect ? q.correctOptionIds : [q.options[0].id],
      isCorrect,
      markedForReview: false,
      skipped: false,
      timeSpentSec: 40 + i * 7,
    }
  })
  return answers
}

export const mockHistory: PracticeSession[] = [
  {
    id: "s-1001",
    exam: "AWS Certified Solutions Architect – Associate",
    examCode: "SAA-C03",
    focusTopics: ["Networking", "Security & Identity"],
    createdAt: new Date(now - day).toISOString(),
    completedAt: new Date(now - day + 18 * 60 * 1000).toISOString(),
    status: "completed",
    questions: SAMPLE_QUESTIONS,
    answers: buildAnswers(SAMPLE_QUESTIONS, 4),
    currentIndex: SAMPLE_QUESTIONS.length,
  },
  {
    id: "s-1000",
    exam: "AWS Certified Solutions Architect – Associate",
    examCode: "SAA-C03",
    focusTopics: ["Storage", "Resilience"],
    createdAt: new Date(now - 3 * day).toISOString(),
    completedAt: new Date(now - 3 * day + 22 * 60 * 1000).toISOString(),
    status: "completed",
    questions: SAMPLE_QUESTIONS,
    answers: buildAnswers(SAMPLE_QUESTIONS, 3),
    currentIndex: SAMPLE_QUESTIONS.length,
  },
]

/** Builds a fresh in-progress session from intake input. */
export function createSessionFromIntake(
  exam: string,
  examCode: string,
  focusTopics: string[],
): PracticeSession {
  return {
    id: `s-${Math.random().toString(36).slice(2, 8)}`,
    exam,
    examCode,
    focusTopics,
    createdAt: new Date().toISOString(),
    status: "in-progress",
    questions: SAMPLE_QUESTIONS,
    answers: {},
    currentIndex: 0,
  }
}
