import type {
  ClarifyingQuestion,
  Confidence,
  LearnTopic,
  PlanCoaching,
  PracticeSession,
  Question,
  StreakSummary,
  StudyPlan,
  TopicLesson,
  TopicLessonContent,
  TopicMastery,
  UserProfile,
} from "@/types"
import { getAllCatalogTopics } from "@/lib/learning/catalog"
import { resolveTopicName } from "@/lib/learning/topic-resolver"
import { buildStudyPlan } from "@/lib/plan/schedule"
import { limitsFor } from "@/lib/config/tiers"

// ---------------------------------------------------------------------------
// Realistic mock content for the Prepa prototype. In production these
// would be generated by the AI backend; here they power a fully interactive UI.
// ---------------------------------------------------------------------------

export const mockProfile: UserProfile = {
  name: "Jordan Avery",
  email: "jordan@certforge.app",
  isAnonymous: false,
  plan: "free",
  subscriptionStatus: null,
  planExpiresAt: null,
  limits: limitsFor("free"),
  dailyLimit: limitsFor("free").questions,
  questionsUsedToday: 8,
  streakDays: 12,
  longestStreak: 21,
  dailyGoal: 10,
  onboardedAt: "2026-01-01T00:00:00Z",
  activeExam: {
    examCode: "SAA-C03",
    exam: "AWS Certified Solutions Architect – Associate",
  },
}


export function buildMockExamTips(): import("@/types").ExamTip[] {
  return [
    {
      title: "Know the format",
      body: "65 questions in 130 minutes — exactly 2 minutes each. 50 are scored, 15 are unscored trial questions, and you need roughly 72% to pass.",
    },
    {
      title: "Read the qualifier first",
      body: "Almost every question ends with MOST cost-effective or MOST operationally efficient. Two answers usually 'work' — the qualifier decides.",
    },
    {
      title: "Prefer managed services",
      body: "When two options both solve the problem, AWS wants the managed, serverless, or multi-AZ one.",
    },
  ]
}

const MOCK_LAB_CONTENT: import("@/types").LabContent = {
  title: "Build a two-tier VPC from scratch",
  scenario:
    "The SAA exam tests whether you can design VPCs with public and private subnets. Building one by hand makes route tables, gateways, and security groups stick.",
  estimatedMinutes: 35,
  costWarning:
    "Everything in this lab is free-tier eligible, but a NAT gateway is NOT — this lab deliberately avoids one. Terminate the t3.micro instance and delete the VPC when done.",
  prerequisites: [
    "An AWS account with admin access (free tier is enough)",
    "AWS CLI installed and configured (optional — console steps included)",
  ],
  steps: [
    { title: "Create the VPC", instruction: "Open the VPC console → Create VPC → IPv4 CIDR 10.0.0.0/16, name it saa-lab. CLI: aws ec2 create-vpc --cidr-block 10.0.0.0/16", hint: "If you don't see 'Create VPC only', switch off the 'VPC and more' wizard." },
    { title: "Create a public subnet", instruction: "Subnets → Create subnet in saa-lab, CIDR 10.0.1.0/24, any AZ. Name it public-a." },
    { title: "Create a private subnet", instruction: "Create a second subnet, CIDR 10.0.2.0/24, same AZ. Name it private-a." },
    { title: "Attach an internet gateway", instruction: "Internet gateways → Create → attach it to saa-lab.", hint: "An unattached IGW does nothing — attaching is a separate action." },
    { title: "Create a public route table", instruction: "Route tables → Create for saa-lab → add route 0.0.0.0/0 → the internet gateway → associate it with public-a." },
    { title: "Launch a test instance", instruction: "EC2 → Launch t3.micro (or t2.micro) Amazon Linux into public-a with auto-assign public IP enabled. Allow SSH from your IP only." },
    { title: "Verify connectivity", instruction: "SSH into the instance's public IP and run: curl -s https://checkip.amazonaws.com" },
    { title: "Prove the private subnet is private", instruction: "Check private-a's route table: it should have only the local 10.0.0.0/16 route — no internet gateway route." },
  ],
  checkpoints: [
    {
      prompt: "What routes does your PRIVATE subnet's route table contain after this lab?",
      options: [
        "Only the local 10.0.0.0/16 route",
        "A 0.0.0.0/0 route to the internet gateway",
        "A 0.0.0.0/0 route to a NAT gateway",
        "No routes at all",
      ],
      correctIndex: 0,
      explanation: "You never associated the private subnet with the public route table, so it keeps only the automatic local route.",
    },
    {
      prompt: "Why could your EC2 instance reach the internet?",
      options: [
        "EC2 instances can always reach the internet",
        "It was in a subnet whose route table sends 0.0.0.0/0 to an attached internet gateway, and it had a public IP",
        "The default security group allows all inbound traffic",
        "AWS automatically adds NAT to every VPC",
      ],
      correctIndex: 1,
      explanation: "Internet access needs all three: an attached IGW, a route to it, and a public IP on the instance.",
    },
  ],
  cleanup: [
    "Terminate the EC2 instance (EC2 → Instances → Terminate).",
    "Delete the VPC (this removes its subnets, route tables, and detaches the IGW).",
    "Delete the internet gateway if it wasn't removed with the VPC.",
    "Open the Billing console → verify no running resources remain.",
  ],
  references: [
    {
      label: "Amazon VPC User Guide",
      url: "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html",
    },
  ],
}

export function buildMockLabCatalog(): {
  supported: boolean
  examCode: string
  exam: string
  items: import("@/types").LabCatalogItem[]
} {
  return {
    supported: true,
    examCode: "SAA-C03",
    exam: DEFAULT_EXAM.exam,
    items: buildMockLearnTopics()
      .filter((t) => t.domainName)
      .map((t, i) => ({
        topicSlug: t.slug,
        topicName: t.topic,
        domainName: t.domainName ?? "",
        domainWeight: t.domainWeight ?? "",
        generated: i === 0,
        status: i === 0 ? "started" : "not-started",
        title: i === 0 ? MOCK_LAB_CONTENT.title : null,
        estimatedMinutes: i === 0 ? MOCK_LAB_CONTENT.estimatedMinutes : null,
      })),
  }
}

export function buildMockTopicLab(
  topicSlug: string,
  started = false,
): import("@/types").TopicLab {
  const topicEntry = buildMockLearnTopics().find((t) => t.slug === topicSlug)
  return {
    id: `lab-${topicSlug}`,
    topicSlug,
    topicName: topicEntry?.topic ?? "Networking",
    exam: DEFAULT_EXAM.exam,
    examCode: DEFAULT_EXAM.examCode,
    status: started ? "started" : "not-started",
    started,
    ...(started
      ? { content: MOCK_LAB_CONTENT }
      : {
          preview: {
            title: MOCK_LAB_CONTENT.title,
            scenario: MOCK_LAB_CONTENT.scenario,
            estimatedMinutes: MOCK_LAB_CONTENT.estimatedMinutes,
            costWarning: MOCK_LAB_CONTENT.costWarning,
            prerequisites: MOCK_LAB_CONTENT.prerequisites,
            stepsCount: MOCK_LAB_CONTENT.steps.length,
            checkpointCount: MOCK_LAB_CONTENT.checkpoints.length,
          },
        }),
    stepsDone: [],
    checkpointScore: null,
    checkpointTotal: null,
    labsUsed: 0,
    labLimit: 1,
  }
}

export function buildMockUserExams(): import("@/types").UserExam[] {
  return [
    {
      examCode: "SAA-C03",
      exam: "AWS Certified Solutions Architect – Associate",
      examDate: "2026-09-15",
      isPreset: true,
    },
    {
      examCode: "DOP-C02",
      exam: "AWS Certified DevOps Engineer – Professional",
      examDate: null,
      isPreset: true,
    },
  ]
}

// Canonical `EXAMCODE::domainId` keys mirror the enriched shape the API
// returns, so mock mode exercises the same blueprint-mapping code as prod.
export const mockTopicMastery: TopicMastery[] = [
  { topic: "SAA-C03::design-resilient", displayTopic: "Networking", domainId: "design-resilient", examCode: "SAA-C03", mastery: 48, questionsAnswered: 64 },
  { topic: "SAA-C03::design-secure", displayTopic: "Security & Identity", domainId: "design-secure", examCode: "SAA-C03", mastery: 56, questionsAnswered: 72 },
  { topic: "SAA-C03::design-high-performing", displayTopic: "Storage", domainId: "design-high-performing", examCode: "SAA-C03", mastery: 81, questionsAnswered: 90 },
  { topic: "SAA-C03::design-resilient", displayTopic: "Compute", domainId: "design-resilient", examCode: "SAA-C03", mastery: 74, questionsAnswered: 58 },
  { topic: "SAA-C03::design-high-performing", displayTopic: "Databases", domainId: "design-high-performing", examCode: "SAA-C03", mastery: 67, questionsAnswered: 41 },
  { topic: "SAA-C03::design-resilient", displayTopic: "Resilience", domainId: "design-resilient", examCode: "SAA-C03", mastery: 62, questionsAnswered: 33 },
]

/** Mastery trend over the last 7 sessions, for the dashboard chart. */
export const mockMasteryTrend = [
  { label: "Mon", mastery: 52 },
  { label: "Tue", mastery: 55 },
  { label: "Wed", mastery: 54 },
  { label: "Thu", mastery: 61 },
  { label: "Fri", mastery: 63 },
  { label: "Sat", mastery: 66 },
  { label: "Sun", mastery: 68 },
]

/** Readiness score trend (recent days), for the sparkline + pace projection. */
export const mockReadinessTrend = (() => {
  const scores = [54, 56, 58, 61, 60, 63, 65, 64, 67, 68, 70]
  const today = new Date(`${new Date().toISOString().slice(0, 10)}T00:00:00Z`)
  const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
  return scores.map((score, i) => {
    const d = new Date(today)
    d.setUTCDate(d.getUTCDate() - (scores.length - 1 - i) * 2)
    const date = d.toISOString().slice(0, 10)
    return { label: `${MONTHS[d.getUTCMonth()]} ${d.getUTCDate()}`, score, date }
  })
})()

/** A streak summary for mock mode, with a realistic 7-day activity row. */
export function buildMockStreak(): StreakSummary {
  const today = new Date().toISOString().slice(0, 10)
  const DAYS = 84 // 12 weeks for the consistency heatmap
  const recent = [12, 10, 0, 14, 11, 10, 6] // last 7 days oldest→newest
  // Deterministic (no Math.random — the store hydrates on server and client)
  // wave of activity that intensifies toward the present.
  const counts = Array.from({ length: DAYS }, (_, i) => {
    if (i >= DAYS - recent.length) return recent[i - (DAYS - recent.length)]
    const wave = (i * 13) % 23
    if (wave < 7) return 0
    return Math.round(Math.min(20, wave * (0.35 + i / DAYS)))
  })
  const activity = counts.map((count, i) => {
    const d = new Date(`${today}T00:00:00Z`)
    d.setUTCDate(d.getUTCDate() - (DAYS - 1 - i))
    return {
      date: d.toISOString().slice(0, 10),
      count,
      goalMet: count >= 10,
    }
  })
  return {
    currentStreak: 12,
    longestStreak: 21,
    dailyGoal: 10,
    questionsToday: counts[counts.length - 1],
    atRisk: false,
    activity,
  }
}

/** Canned AI coaching for mock mode (no AI call). */
export const mockPlanCoaching: PlanCoaching = {
  headline: "On track — but Cost-Optimized is your soft spot.",
  message:
    "You're pacing well for your exam date and your mock scores are trending up. The biggest lever now is Cost-Optimized Architectures at 35% — a few focused sessions there will move your weighted score the most. Keep the weekly mock exams; they're your best readiness signal.",
  domainTips: [
    { domain: "Cost-Optimized", tip: "Drill S3 storage classes, EC2 pricing models, and when to use Savings Plans vs Reserved Instances." },
    { domain: "Secure", tip: "Focus on IAM policy evaluation, KMS key policies, and VPC endpoint security." },
    { domain: "Resilient", tip: "Review multi-AZ vs multi-Region patterns and RTO/RPO trade-offs." },
  ],
}

/** A realistic in-progress study plan for mock mode. */
export function buildMockStudyPlan(): StudyPlan {
  const today = new Date().toISOString().slice(0, 10)
  const target = new Date()
  target.setDate(target.getDate() + 21)
  const built = buildStudyPlan({
    examCode: "SAA-C03",
    targetScore: 75,
    startDate: today,
    targetDate: target.toISOString().slice(0, 10),
    dailyLimit: 20,
    fullExamQuestionCount: 65,
    domains: [
      { id: "design-resilient", name: "Design Resilient Architectures", weightPercent: 26, mastery: 60 },
      { id: "design-high-performing", name: "Design High-Performing Architectures", weightPercent: 24, mastery: 75 },
      { id: "design-secure", name: "Design Secure Architectures", weightPercent: 30, mastery: 55 },
      { id: "design-cost-optimized", name: "Design Cost-Optimized Architectures", weightPercent: 20, mastery: 35 },
    ],
  })
  return {
    id: "mock-plan-1",
    examCode: "SAA-C03",
    exam: "AWS Certified Solutions Architect – Associate",
    startDate: built.startDate,
    targetDate: built.targetDate,
    targetScore: built.targetScore,
    projectedScore: built.projectedScore,
    restDays: [],
    effort: "standard",
    tasks: built.tasks.map((t, i) => ({
      id: `mock-task-${i}`,
      dayIndex: t.dayIndex,
      scheduledDate: t.date,
      type: t.type,
      domainId: t.domainId,
      domainName: t.domainName,
      questionCount: t.questionCount,
      title: t.title,
      rationale: t.rationale,
      // Mark the first two days complete for a believable "in progress" demo.
      status: t.dayIndex < 2 ? "done" : "pending",
    })),
  }
}

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q1",
    topic: "Networking",
    difficulty: "medium",
    multiSelect: false,
    prompt:
      "A company runs a public-facing web application in a VPC. The security team requires that instances in the private subnet can download OS patches from the internet, but must not be reachable from the internet directly. Which solution meets these requirements?",
    options: [
      { id: "a", text: "Attach an internet gateway to the private subnet route table." },
      { id: "b", text: "Deploy a NAT gateway in a public subnet and route private subnet traffic through it." },
      { id: "c", text: "Assign Elastic IP addresses to each private instance." },
      { id: "d", text: "Create a VPC peering connection to a shared services VPC." },
    ],
    correctOptionIds: ["b"],
    explanation:
      "A NAT gateway lets instances in a private subnet initiate outbound connections to the internet (for patches, updates) while preventing the internet from initiating inbound connections. The NAT gateway lives in a public subnet, and the private subnet route table sends 0.0.0.0/0 to the NAT gateway. Attaching an internet gateway directly would make the subnet public, and Elastic IPs would expose the instances.",
    references: [
      { label: "AWS Docs — NAT gateways", url: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html" },
    ],
  },
  {
    id: "q2",
    topic: "Security & Identity",
    difficulty: "hard",
    multiSelect: true,
    prompt:
      "You need to grant an application running on an EC2 instance access to an S3 bucket following least-privilege best practices. Which TWO actions should you take?",
    options: [
      { id: "a", text: "Create an IAM role with a scoped S3 policy and attach it to the instance via an instance profile." },
      { id: "b", text: "Store long-lived IAM user access keys in the application's config file." },
      { id: "c", text: "Restrict the policy to the specific bucket and required actions only." },
      { id: "d", text: "Grant the role the AdministratorAccess managed policy for simplicity." },
    ],
    correctOptionIds: ["a", "c"],
    explanation:
      "Best practice is to use an IAM role attached through an instance profile so the application receives temporary, automatically-rotated credentials — never long-lived keys in config files. The attached policy should be scoped to only the specific bucket and the minimum actions required, which is the essence of least privilege. AdministratorAccess violates least privilege.",
    references: [
      { label: "AWS Docs — IAM roles for EC2", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html" },
    ],
  },
  {
    id: "q3",
    topic: "Storage",
    difficulty: "easy",
    multiSelect: false,
    prompt:
      "Which S3 storage class is most cost-effective for data that is accessed roughly once a quarter and must be retrieved within milliseconds when needed?",
    options: [
      { id: "a", text: "S3 Standard" },
      { id: "b", text: "S3 Standard-Infrequent Access (Standard-IA)" },
      { id: "c", text: "S3 Glacier Deep Archive" },
      { id: "d", text: "S3 One Zone-IA" },
    ],
    correctOptionIds: ["b"],
    explanation:
      "S3 Standard-IA is designed for data that is accessed less frequently but requires rapid (millisecond) access when needed. It has a lower storage cost than S3 Standard with a per-GB retrieval fee. Glacier Deep Archive has retrieval times of hours, and One Zone-IA sacrifices multi-AZ resilience.",
    references: [
      { label: "AWS Docs — S3 storage classes", url: "https://aws.amazon.com/s3/storage-classes/" },
    ],
  },
  {
    id: "q4",
    topic: "Resilience",
    difficulty: "medium",
    multiSelect: false,
    prompt:
      "An application must remain available even if an entire Availability Zone fails. Which architecture best achieves this for a stateless web tier behind a load balancer?",
    options: [
      { id: "a", text: "A single large EC2 instance with an Elastic IP." },
      { id: "b", text: "An Auto Scaling group spanning multiple AZs behind an Application Load Balancer." },
      { id: "c", text: "Two instances in the same AZ with a standby instance." },
      { id: "d", text: "A vertically scaled instance in one AZ with frequent snapshots." },
    ],
    correctOptionIds: ["b"],
    explanation:
      "Spreading an Auto Scaling group across multiple Availability Zones behind an Application Load Balancer ensures that if one AZ fails, the ALB routes traffic to healthy instances in the remaining AZs and Auto Scaling replaces unhealthy capacity. Single-AZ designs cannot survive an AZ failure.",
    references: [
      { label: "AWS Docs — Distributing instances across AZs", url: "https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html" },
    ],
  },
  {
    id: "q5",
    topic: "Databases",
    difficulty: "medium",
    multiSelect: false,
    prompt:
      "A read-heavy application using Amazon RDS for MySQL is experiencing high read latency during peak hours. Which change most directly improves read scalability without changing the application's write path?",
    options: [
      { id: "a", text: "Enable Multi-AZ deployment." },
      { id: "b", text: "Add RDS read replicas and direct read traffic to them." },
      { id: "c", text: "Increase the backup retention period." },
      { id: "d", text: "Switch the instance to a burstable instance class." },
    ],
    correctOptionIds: ["b"],
    explanation:
      "Read replicas offload read traffic from the primary, improving read scalability and lowering latency for read-heavy workloads. Multi-AZ is for high availability/failover (the standby does not serve reads), and increasing backup retention does not affect read performance.",
    references: [
      { label: "AWS Docs — RDS read replicas", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html" },
    ],
  },
  {
    id: "q6",
    topic: "Storage",
    difficulty: "medium",
    questionType: "select_grid",
    prompt:
      "For each of the following statements about Amazon S3 storage classes, select Yes if the statement is true, otherwise select No.",
    dragData: {
      type: "select_grid",
      rows: [
        { id: "r1", statement: "S3 Standard-IA charges a per-GB retrieval fee." },
        { id: "r2", statement: "S3 Glacier Deep Archive offers millisecond retrieval by default." },
        { id: "r3", statement: "S3 Intelligent-Tiering moves objects between tiers automatically." },
      ],
      columns: [
        { id: "yes", label: "Yes" },
        { id: "no", label: "No" },
      ],
      correctByRow: { r1: "yes", r2: "no", r3: "yes" },
    },
    correctOptionIds: [],
    explanation:
      "Standard-IA has lower storage cost but charges per-GB retrieval. Glacier Deep Archive is the lowest-cost class with retrieval times of hours, not milliseconds. Intelligent-Tiering automatically moves objects between access tiers based on usage.",
    references: [
      { label: "AWS Docs — S3 storage classes", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html" },
    ],
  },
  {
    id: "q7",
    topic: "Networking",
    difficulty: "medium",
    questionType: "command_input",
    scenario:
      "You are connected to a Cisco router in privileged EXEC mode and need to make configuration changes.",
    prompt: "Type the command that enters global configuration mode.",
    options: [],
    dragData: {
      type: "command_input",
      commandContext: "Router#",
      acceptedAnswers: ["configure terminal", "conf t", "config t"],
    },
    correctOptionIds: [],
    explanation:
      "configure terminal (commonly abbreviated conf t) moves from privileged EXEC mode into global configuration mode, where device-wide settings are changed.",
    references: [
      { label: "Cisco Learning Network: CCNA exam topics", url: "https://learningnetwork.cisco.com/s/ccna-exam-topics" },
    ],
  },
]

/** Mock team for org-account mock mode. */
export function buildMockTeam(): import("@/types").Team {
  const today = new Date().toISOString().slice(0, 10)
  const yesterday = new Date(Date.now() - 86_400_000).toISOString().slice(0, 10)
  return {
    id: "org-1",
    name: "Cloud Bootcamp · Cohort 7",
    role: "owner",
    plan: "team",
    seats: 8,
    seatsUsed: 4,
    subscriptionStatus: "active",
    targetExamCode: "SAA-C03",
    targetExam: "AWS Certified Solutions Architect – Associate",
    members: [
      { userId: "u-jordan", name: "Jordan Avery", email: "jordan@certforge.app", role: "owner", overallMastery: 65, questionsAnswered: 358, weeklyQuestions: 84, streakDays: 12, lastActiveDate: today },
      { userId: "u-sam", name: "Sam Okoye", email: "sam@example.com", role: "member", overallMastery: 78, questionsAnswered: 512, weeklyQuestions: 121, streakDays: 5, lastActiveDate: today },
      { userId: "u-mia", name: "Mia Chen", email: "mia@example.com", role: "member", overallMastery: 44, questionsAnswered: 96, weeklyQuestions: 0, streakDays: 0, lastActiveDate: yesterday },
      { userId: "u-leo", name: "Leo Martins", email: "leo@example.com", role: "admin", overallMastery: 71, questionsAnswered: 240, weeklyQuestions: 45, streakDays: 21, lastActiveDate: today },
    ],
  }
}

/** Mock invite links for the team settings panel. */
export function buildMockTeamInvites(): import("@/types").TeamInvite[] {
  return [
    {
      token: "mock-invite-token",
      createdAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
      expiresAt: new Date(Date.now() + 12 * 86_400_000).toISOString(),
      email: null,
    },
    {
      token: "mock-email-invite",
      createdAt: new Date(Date.now() - 86_400_000).toISOString(),
      expiresAt: new Date(Date.now() + 13 * 86_400_000).toISOString(),
      email: "newhire@example.com",
    },
  ]
}

/** Mock team subscription for the billing panel. */
export function buildMockTeamBilling(): import("@/types").TeamBilling {
  return {
    hasSubscription: true,
    status: "active",
    seats: 8,
    nextBilledAt: new Date(Date.now() + 21 * 86_400_000).toISOString(),
    cancelEffectiveAt: null,
    updatePaymentUrl: null,
  }
}

/** Mock team assignments for the assignments tab. */
export function buildMockTeamAssignments(): import("@/types").TeamAssignment[] {
  return [
    {
      id: "ta-1",
      title: "Week 4 checkpoint mock",
      exam: "AWS Certified Solutions Architect – Associate",
      examCode: "SAA-C03",
      questionCount: 30,
      durationSec: 3600,
      passMark: 72,
      dueAt: new Date(Date.now() + 5 * 86_400_000).toISOString(),
      createdAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
      createdBy: "u-jordan",
      completedCount: 2,
      myAttempt: { sessionId: "s-1000", status: "completed", correct: 24, answered: 30 },
    },
    {
      id: "ta-2",
      title: "Networking deep-dive",
      exam: "AWS Certified Solutions Architect – Associate",
      examCode: "SAA-C03",
      questionCount: 20,
      durationSec: 2400,
      passMark: 72,
      dueAt: null,
      createdAt: new Date(Date.now() - 86_400_000).toISOString(),
      createdBy: "u-jordan",
      completedCount: 0,
      myAttempt: null,
    },
  ]
}

/** Mock per-member results for a team assignment. */
export function buildMockTeamAssignmentResults(): import("@/types").TeamAssignmentResults {
  const [assignment] = buildMockTeamAssignments()
  return {
    assignment,
    members: [
      { userId: "u-jordan", name: "Jordan Avery", email: "jordan@certforge.app", status: "completed", correct: 24, answered: 30, timeUsedSec: 2900, completedAt: new Date().toISOString() },
      { userId: "u-sam", name: "Sam Okoye", email: "sam@example.com", status: "completed", correct: 27, answered: 30, timeUsedSec: 2400, completedAt: new Date().toISOString() },
      { userId: "u-mia", name: "Mia Chen", email: "mia@example.com", status: "in-progress", correct: 6, answered: 11, timeUsedSec: null, completedAt: null },
      { userId: "u-leo", name: "Leo Martins", email: "leo@example.com", status: "not-started", correct: 0, answered: 0, timeUsedSec: null, completedAt: null },
    ],
  }
}

/** Mock saved questions for the bookmarks list. */
export function buildMockBookmarks() {
  const ids = ["q2", "q4"]
  const ts = Date.now()
  return SAMPLE_QUESTIONS.filter((q) => ids.includes(q.id)).map((question, i) => ({
    questionId: question.id,
    exam: "AWS Certified Solutions Architect – Associate",
    examCode: "SAA-C03",
    createdAt: new Date(ts - i * 86_400_000).toISOString(),
    question,
  }))
}

/** Mock missed questions (a few wrong-answered samples) for flashcards/review. */
export function buildMockMissedQuestions() {
  const missedIds = ["q1", "q3", "q5"]
  const ts = Date.now()
  return SAMPLE_QUESTIONS.filter((q) => missedIds.includes(q.id)).map(
    (question, i) => ({
      questionId: question.id,
      sessionId: "s-1001",
      exam: "AWS Certified Solutions Architect – Associate",
      examCode: "SAA-C03",
      answeredAt: new Date(ts - i * 3600_000).toISOString(),
      question,
    }),
  )
}

export const mockClarifyingQuestions: ClarifyingQuestion[] = [
  {
    id: "c1",
    question: "Which exam attempt date are you targeting?",
    suggestions: ["Within 2 weeks", "1-2 months", "Just exploring"],
  },
  {
    id: "c2",
    question: "How would you rate your current networking knowledge?",
    suggestions: ["Beginner", "Intermediate", "Confident"],
  },
  {
    id: "c3",
    question: "Preferred question difficulty to start with?",
    suggestions: ["Mixed", "Mostly hard", "Ease me in"],
  },
]

const now = Date.now()
const day = 24 * 60 * 60 * 1000

function buildAnswers(
  questions: Question[],
  correctCount: number,
  withConfidence = false,
): PracticeSession["answers"] {
  const answers: PracticeSession["answers"] = {}
  questions.forEach((q, i) => {
    const isCorrect = i < correctCount
    answers[q.id] = {
      questionId: q.id,
      selectedOptionIds: isCorrect
        ? (q.correctOptionIds ?? [])
        : [q.options?.[0]?.id ?? "a"],
      isCorrect,
      markedForReview: false,
      skipped: false,
      timeSpentSec: 40 + i * 7,
      // Spread across the confidence quadrants so the debrief matrix and
      // dashboard confidence insights have something to show.
      ...(withConfidence && {
        confidence: (i % 3 === 0 ? "unsure" : "sure") as Confidence,
      }),
    }
  })
  return answers
}

export const mockHistory: PracticeSession[] = [
  {
    id: "s-1001",
    exam: "AWS Certified Solutions Architect – Associate",
    examCode: "SAA-C03",
    focusTopics: ["Networking", "Security & Identity"],
    createdAt: new Date(now - day).toISOString(),
    completedAt: new Date(now - day + 18 * 60 * 1000).toISOString(),
    status: "completed",
    questions: SAMPLE_QUESTIONS,
    answers: buildAnswers(SAMPLE_QUESTIONS, 4),
    currentIndex: SAMPLE_QUESTIONS.length,
  },
  {
    id: "s-1000",
    exam: "AWS Certified Solutions Architect – Associate",
    examCode: "SAA-C03",
    focusTopics: ["Storage", "Resilience"],
    createdAt: new Date(now - 3 * day).toISOString(),
    completedAt: new Date(now - 3 * day + 22 * 60 * 1000).toISOString(),
    status: "completed",
    questions: SAMPLE_QUESTIONS,
    answers: buildAnswers(SAMPLE_QUESTIONS, 3),
    currentIndex: SAMPLE_QUESTIONS.length,
  },
  // Two completed mocks so the score trend and confidence widgets render.
  {
    id: "e-1001",
    exam: "AWS Certified Solutions Architect – Associate",
    examCode: "SAA-C03",
    focusTopics: ["Full exam simulation"],
    createdAt: new Date(now - 2 * day).toISOString(),
    completedAt: new Date(now - 2 * day + 80 * 60 * 1000).toISOString(),
    status: "completed",
    questions: SAMPLE_QUESTIONS,
    answers: buildAnswers(SAMPLE_QUESTIONS, 6, true),
    currentIndex: SAMPLE_QUESTIONS.length,
    mode: "exam",
    durationSec: 90 * 60,
    passMark: 72,
  },
  {
    id: "e-1000",
    exam: "AWS Certified Solutions Architect – Associate",
    examCode: "SAA-C03",
    focusTopics: ["Full exam simulation"],
    createdAt: new Date(now - 6 * day).toISOString(),
    completedAt: new Date(now - 6 * day + 85 * 60 * 1000).toISOString(),
    status: "completed",
    questions: SAMPLE_QUESTIONS,
    answers: buildAnswers(SAMPLE_QUESTIONS, 4, true),
    currentIndex: SAMPLE_QUESTIONS.length,
    mode: "exam",
    durationSec: 90 * 60,
    // DEFAULT_EXAM is declared below this initializer — literal to avoid TDZ.
    passMark: 72,
  },
]

/** Builds a fresh in-progress session from intake input. */
export function createSessionFromIntake(
  exam: string,
  examCode: string,
  focusTopics: string[],
): PracticeSession {
  return {
    id: `s-${Math.random().toString(36).slice(2, 8)}`,
    exam,
    examCode,
    focusTopics,
    createdAt: new Date().toISOString(),
    status: "in-progress",
    questions: SAMPLE_QUESTIONS,
    answers: {},
    currentIndex: 0,
    mode: "practice",
  }
}

/**
 * Builds `count` exam questions. With only a handful of mock questions
 * available we cycle through the sample set, giving each a unique id so
 * answers and React keys stay distinct.
 */
export function buildExamQuestions(count: number): Question[] {
  return Array.from({ length: count }, (_, i) => {
    const base = SAMPLE_QUESTIONS[i % SAMPLE_QUESTIONS.length]
    return { ...base, id: `${base.id}-${i + 1}` }
  })
}

export interface ExamConfig {
  questionCount: number
  durationSec: number
  exam?: string
  examCode?: string
}

/** Default exam used by the simulator until the backend supplies real ones. */
export const DEFAULT_EXAM = {
  exam: "AWS Certified Solutions Architect – Associate",
  examCode: "SAA-C03",
  /** Real-world reference: 65 questions in 130 minutes, 72% to pass. */
  realistic: { questionCount: 65, durationMin: 130 },
  passMark: 72,
}

/** Builds a fresh, timed exam session. */
export function createExamSession({
  questionCount,
  durationSec,
  exam = DEFAULT_EXAM.exam,
  examCode = DEFAULT_EXAM.examCode,
}: ExamConfig): PracticeSession {
  return {
    id: `e-${Math.random().toString(36).slice(2, 8)}`,
    exam,
    examCode,
    focusTopics: ["Full exam simulation"],
    createdAt: new Date().toISOString(),
    status: "in-progress",
    questions: buildExamQuestions(questionCount),
    answers: {},
    currentIndex: 0,
    mode: "exam",
    durationSec,
    passMark: DEFAULT_EXAM.passMark,
  }
}

const MOCK_LESSON_CONTENT: TopicLessonContent = {
  deepDive: [
    {
      title: "VPC fundamentals",
      body:
        "A Virtual Private Cloud (VPC) is your isolated network in AWS. Public subnets route to an internet gateway for inbound/outbound internet access. Private subnets have no direct internet route — outbound access typically flows through a NAT gateway in a public subnet.",
    },
    {
      title: "NAT gateway pattern",
      body:
        "Place NAT gateways in public subnets (one per AZ for HA). Update private subnet route tables to send 0.0.0.0/0 to the NAT gateway. This lets private instances download patches without accepting inbound connections from the internet.",
    },
    {
      title: "Security groups vs NACLs",
      body:
        "Security groups are stateful firewalls at the instance/ENI level — return traffic is automatically allowed. Network ACLs are stateless subnet-level filters evaluated in order. Exams often test which layer to use for a given access pattern.",
    },
  ],
  comparisons: [
    {
      title: "Security groups vs Network ACLs",
      columns: ["Aspect", "Security group", "Network ACL"],
      rows: [
        ["Level", "Instance / ENI", "Subnet"],
        ["State", "Stateful — return traffic allowed", "Stateless — both directions needed"],
        ["Rules", "Allow only", "Allow and deny"],
        ["Evaluation", "All rules", "In number order, first match wins"],
      ],
    },
    {
      title: "NAT gateway vs NAT instance",
      columns: ["Aspect", "NAT gateway", "NAT instance"],
      rows: [
        ["Management", "Fully managed", "You patch and scale it"],
        ["Availability", "HA within an AZ", "Single EC2 instance"],
        ["Bandwidth", "Scales to 100 Gbps", "Depends on instance type"],
      ],
    },
  ],
  commonTraps: [
    "Attaching an internet gateway directly to a private subnet route table",
    "Using long-lived IAM user keys on EC2 instead of instance profiles",
    "Confusing security group stateful behavior with NACL stateless rules",
    "Choosing VPC peering when Transit Gateway is better for hub-and-spoke",
  ],
  keyFacts: [
    {
      fact: "Security groups are stateful; NACLs are stateless",
      question: "Which VPC firewall layer is stateful, and which is stateless?",
    },
    {
      fact: "A NAT gateway lives in a public subnet and scales to 100 Gbps",
      question: "Where does a NAT gateway live, and how much bandwidth can it scale to?",
    },
    {
      fact: "One NAT gateway per AZ is the HA pattern",
      question: "What is the high-availability deployment pattern for NAT gateways?",
    },
    {
      fact: "Gateway VPC endpoints (S3, DynamoDB) are free; interface endpoints are billed hourly",
      question: "Which VPC endpoint type is free, and for which services?",
    },
    {
      fact: "Route 53 private hosted zones resolve only inside associated VPCs",
      question: "Where do Route 53 private hosted zones resolve?",
    },
  ],
  recap:
    "For exam scenarios about private subnet outbound access, NAT gateway in a public subnet is the standard answer. Remember security groups are stateful and operate at the instance level, while NACLs are stateless and subnet-level. Multi-AZ NAT gateways improve availability.",
  checkQuestions: [
    {
      prompt:
        "Instances in a private subnet need to download OS patches. What provides outbound internet access without allowing inbound connections?",
      options: [
        "An internet gateway attached to the private subnet",
        "A NAT gateway in a public subnet, referenced from the private route table",
        "A VPC peering connection to a public VPC",
        "An interface VPC endpoint for the internet",
      ],
      correctIndex: 1,
      explanation:
        "NAT gateways give private instances outbound-only internet access; internet gateways would allow inbound too.",
    },
    {
      prompt: "Which statement about security groups is true?",
      options: [
        "They are stateless and evaluated in rule order",
        "They support explicit deny rules",
        "They are stateful — return traffic is automatically allowed",
        "They apply at the subnet level",
      ],
      correctIndex: 2,
      explanation:
        "Security groups are stateful, instance-level, allow-only firewalls; NACLs are the stateless subnet-level ones.",
    },
    {
      prompt:
        "Private EC2 instances need to reach S3 without traversing the internet at no extra cost. Which option fits?",
      options: [
        "Gateway VPC endpoint",
        "Interface VPC endpoint",
        "NAT gateway",
        "Transit Gateway",
      ],
      correctIndex: 0,
      explanation:
        "Gateway endpoints for S3 and DynamoDB are free and keep traffic on the AWS network.",
    },
    {
      prompt: "What is the recommended NAT gateway pattern for high availability?",
      options: [
        "One NAT gateway shared by all AZs",
        "One NAT gateway per Availability Zone",
        "Two NAT gateways in the same subnet",
        "A NAT instance with an Auto Scaling group",
      ],
      correctIndex: 1,
      explanation:
        "A NAT gateway is resilient within a single AZ, so you deploy one per AZ to survive AZ failure.",
    },
  ],
  references: [
    {
      label: "AWS VPC User Guide",
      url: "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html",
    },
    {
      label: "AWS NAT Gateways",
      url: "https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html",
    },
  ],
}

export function buildMockLearnTopics(): LearnTopic[] {
  const assessed: LearnTopic[] = mockTopicMastery.map((t) => {
    const resolved = resolveTopicName(t.displayTopic ?? t.topic, "SAA-C03")
    const hasAi = t.mastery < 70
    return {
      topic: t.displayTopic ?? t.topic,
      slug: resolved.slug,
      mastery: t.mastery,
      questionsAnswered: t.questionsAnswered,
      assessed: true,
      domainName: resolved.catalogTopic?.domainName,
      domainWeight: resolved.catalogTopic?.domainWeight,
      lessonId: hasAi ? `lesson-${resolved.slug}` : undefined,
      lessonStatus: hasAi
        ? t.mastery < 55
          ? "started"
          : "not-started"
        : "not-started",
      bookmarked: resolved.slug === "networking",
      hasAiContent: hasAi && t.mastery < 55,
      hasLab: Boolean(resolved.catalogTopic?.domainName),
    }
  })

  const assessedSlugs = new Set(assessed.map((t) => t.slug))
  const unassessed: LearnTopic[] = getAllCatalogTopics("SAA-C03")
    .filter((c) => !assessedSlugs.has(c.slug))
    .map((c) => ({
      topic: c.name,
      slug: c.slug,
      mastery: 0,
      questionsAnswered: 0,
      assessed: false,
      domainName: c.domainName,
      domainWeight: c.domainWeight,
      lessonStatus: "not-started",
      bookmarked: false,
      hasAiContent: false,
      hasLab: true,
    }))

  return [...assessed, ...unassessed]
}

export function buildMockFactCards(): import("@/types").FactCard[] {
  return buildMockLearnTopics()
    .filter((t) => t.hasAiContent && t.lessonId)
    .flatMap((t) =>
      (MOCK_LESSON_CONTENT.keyFacts ?? []).map((f, i) => ({
        lessonId: t.lessonId!,
        factIndex: i,
        topicName: t.topic,
        question: f.question,
        fact: f.fact,
        due: true,
        nextReviewAt: null,
      })),
    )
}

export function buildMockTopicLesson(topicSlug: string): TopicLesson {
  const topicEntry = buildMockLearnTopics().find((t) => t.slug === topicSlug)
  const topicName =
    topicEntry?.topic ??
    topicSlug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())

  const resolved = resolveTopicName(topicName, "SAA-C03")
  const catalogTopic = resolved.catalogTopic

  return {
    id: topicEntry?.lessonId ?? `lesson-${topicSlug}`,
    topicSlug,
    topicName,
    exam: DEFAULT_EXAM.exam,
    examCode: DEFAULT_EXAM.examCode,
    provider: "aws",
    mastery: topicEntry?.mastery ?? 50,
    questionsAnswered: topicEntry?.questionsAnswered ?? 0,
    domainName: catalogTopic?.domainName ?? "General",
    domainWeight: catalogTopic?.domainWeight ?? "—",
    outline: catalogTopic?.outline ?? [
      "Core concepts for this topic",
      "Key terminology and definitions",
      "Common exam scenarios",
    ],
    curatedReferences: catalogTopic?.references ?? [],
    content: topicEntry?.hasAiContent ? MOCK_LESSON_CONTENT : undefined,
    status: topicEntry?.lessonStatus ?? "not-started",
    bookmarked: topicEntry?.bookmarked ?? false,
    lessonsUsedToday: 1,
    dailyLessonLimit: 3,
  }
}

export function generateMockTopicLesson(topicSlug: string): TopicLesson {
  const lesson = buildMockTopicLesson(topicSlug)
  return {
    ...lesson,
    content: MOCK_LESSON_CONTENT,
    status: "started",
    lessonsUsedToday: Math.min(3, (lesson.lessonsUsedToday ?? 0) + 1),
  }
}
